[InputMethod]
Name=ilo-sitelen
Icon=*
LangCode=*
Addon=table
Configurable=True

[Table]
File=table/ijo-sitelen.dict
OrderPolicy=None
AutoSelect=True
ExactMatch=False
UseAlternativePageKey=True
FirstCandidateAsPreedit=True
CommitInvalidSegment=False
Hint=True
